---
- name: test playbook
  hosts: dc01.winadmin.me
  gather_facts: true
  tasks:
    - name: ComputerSystem
      win_shell: Get-WmiObject Win32_ComputerSystem
      register: cs

    - mail:
        host: mail01.winadmin.me
        username: admin@winadmin.me
        password: P@ssw0rd
        to: venu@winadmin.me
        subject: Mail from Ansible
        body: Hello there!
      delegate_to: localhost
      run_once: True

    - debug:
        msg: "{{ ansible_facts['distribution'] }}"