---
- name: test playbook
  hosts: all
  gather_facts: true
  tasks:
    - name: ComputerSystem
      win_shell: Get-WmiObject Win32_ComputerSystem
      register: cs

    - win_mail:
        host: mail01.winadmin.me
        to: venu@winadmin.me
        subject: Mail from Ansible
        body: "{{ansible_facts}}"

    - debug:
        msg: "{{ ansible_facts['distribution'] }}"